CREATE DATABASE IF NOT EXISTS email_project1;
USE email_project1;

CREATE TABLE IF NOT EXISTS subscribers1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELETE FROM subscribers1;
SET SQL_SAFE_UPDATES = 0;
ALTER TABLE subscribers1 AUTO_INCREMENT = 1;
